### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by mkitti** [conda-forge/openspecfun-feedstock#10]
### Comment:

I am interested in maintaining the openspecfun feedstock.

We need an updated version of openspecfun to replace binary artifacts in https://github.com/conda-forge/pysr-feedstock

cc: @conda-forge/pysr @ngam @MilesCranmer @isuruf

**Comment by ngam** [comment]
put this in the title of a new issue. It seems like this feedstock can use all the help it can get!

@conda-forge-admin, please add user @mkitti

**Comment by ngam** [comment]
you may want to either explicitly ask the maintainer or core later on. Usually, some people prefer that you show some "activity" before being considered. The rationale is that there often is a specific reason/action you want to be a maintainer so that you can commit it to the repo, so if you could start a PR with that and then the maintainers/core can consider you as part or in light of the PR. Does that make sense? I suspect you want to sync this or make it readily available for julia builds, so that could be a good reason

**Comment by mkitti** [comment]
I would be pretty happy if someone merged #8 or #9.
